package ru.musintimur.instastat.common.constants

const val ENV_INSTASTAT_STATIC_FOLDER = "INSTASTAT_STATIC_FOLDER"
const val ENV_FIREFOX_BIN_PATH = "FIREFOX_BIN_PATH"
const val ENV_GECKO_BIN_PATH = "GECKO_BIN_PATH"
const val ENV_LOGGING = "LOGGING"
const val ENV_ERROR_LOGGING = "ERROR_LOGGING"
const val ENV_SERVER_HOST = "PG_SERVER_HOST"
const val ENV_SERVER_PORT = "PG_SERVER_PORT"
const val ENV_DATABASE_NAME = "PG_DATABASE_NAME"
const val ENV_SCHEMA = "PG_SCHEMA"
const val ENV_DB_USER = "PG_USERNAME"
const val ENV_DB_PASSWORD = "PG_PASSWORD"